FROM python:3.12-slim

WORKDIR /app
# Ускоряем колёса
RUN pip install --no-cache-dir uv
COPY requirements.lock /app/requirements.lock
RUN uv pip install --system -r requirements.lock

COPY src/api /app/src/api
ENV PYTHONPATH=/app
EXPOSE 8000
CMD ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
